name: "[CI] init workflows"

on:
  workflow_dispatch:
    inputs:
      dest:
        description: 'target repository({repository_name} or {topic1/topic2})'
        required: true
        default: 'identity'
      type:
        description: 'type of deployment ({repository} or {topic})'
        required: true
        default: 'repository'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 'init'
    steps:
      - uses: actions/checkout@v2
      - name: set git user
        run : git config --global user.email admin@cloudforet.io
      - name: set python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: install requirements
        run: pip install -r requirements.txt
      - name: set PAT_TOKEN env
        run: echo "PAT_TOKEN=$(echo ${{ secrets.PAT_TOKEN }})" >> $GITHUB_ENV
      - name: init workflows
        run: |
          python src/main.py --repo ${{ github.event.inputs.dest }} --type ${{ github.event.inputs.type }}
